// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Editable: typeof import('./src/components/Editable.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Toggle: typeof import('./src/components/Toggle.vue')['default']
  }
}

export { }
