// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Editable: typeof import('./src/components/Editable.vue')['default']
    Form: typeof import('./src/components/Form.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IFluentReOrderDotsHorizontal16Filled: typeof import("~icons/fluent/re-order-dots-horizontal16-filled")["default"]
    'IMdi:close': typeof import('~icons/mdi/close')['default']
    'IMdi:github': typeof import('~icons/mdi/github')['default']
    'IMdi:plus': typeof import('~icons/mdi/plus')['default']
    IPhDotsSixBold: typeof import('~icons/ph/dots-six-bold')['default']
    Modal: typeof import('./src/components/Modal.vue')['default']
    Preview: typeof import('./src/components/Preview.vue')['default']
    Toggle: typeof import('./src/components/Toggle.vue')['default']
    Upload: typeof import('./src/components/Upload.vue')['default']
  }
}

export { }
