// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Editable: typeof import('./src/components/Editable.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IFluentReOrderDotsHorizontal16Filled: typeof import('~icons/fluent/re-order-dots-horizontal16-filled')['default']
    'IMdi:close': typeof import('~icons/mdi/close')['default']
    IPhDotsSixBold: typeof import('~icons/ph/dots-six-bold')['default']
    Preview: typeof import('./src/components/Preview.vue')['default']
    Toggle: typeof import('./src/components/Toggle.vue')['default']
  }
}

export { }
