export const referenceFormat: { [key: string]: string } = {
  uuid: "text",
  text: "text",
  char: "text",
  character: "text",
  varchar: "text",
  ARRAY: "unknown",
  boolean: "checkbox",
  date: "date",
  time: "time",
  timestamp: "datetime-local",
  timestamptz: "datetime-local",
  interval: "number",
  json: "json",
  smallint: "number",
  int: "number",
  integer: "number",
  bigint: "number",
  float: "number",
  float8: "number",
  enum: "select",
}

export const referencePlaceholder: { [key: string]: string | boolean | number | Date | undefined } = {
  uuid: "123e4567-e89b-12d3-a456-426614174000",
  text: "Supabase is cool!",
  char: "Supabase is cool!",
  character: "Supabase is cool!",
  varchar: "Supabase is cool!",
  ARRAY: undefined,
  boolean: false,
  date: Date.now(),
  time: Date.now(),
  timestamp: Date.now(),
  timestamptz: Date.now(),
  interval: 0,
  json: `{ "Supabase": "is cool!" }`,
  smallint: 0,
  int: 0,
  integer: 0,
  bigint: 0,
  float: 0,
  float8: 0,
  enum: undefined,
}
